# @package _global_

defaults:
  - _self_
  - data: rugd
  - model: binary_seg
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

  - evaluation: radio_cnn # ensures model.net is defined for checkpoint evaluation

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ???

model:
  strict_loading: false

paths:
  root_dir: /home/fletford/Documents/flynn-fork-wildos/nebula2-wildos/training/explorfm_trainer
  data_dir: /home/fletford/Documents/flynn-fork-wildos/nebula2-wildos/training/data
