# @package _global_

defaults:
  - override /data: rugd
  - override /model: binary_seg
  - override /logger: wandb
  - override /trainer: gpu

tags: ["eval", "RADIO", "c-radio_v3-b", "radio_cnn"]

ckpt_path: null

model:
  net:
    _target_: src.models.components.radio_cnn.RADIO_CNN
    model_version: "c-radio_v3-b"
    adaptor_version: null
    use_naclip: true
  vmax: 1.0

logger:
  wandb:
    tags: ${tags}
    project: "TraversabilitySegmentation"
    entity: "objsearch-jpl"
    name: eval_rugd_radio_cnn

paths:
  root_dir: /home/fletford/Documents/flynn-fork-wildos/nebula2-wildos/training/explorfm_trainer
  data_dir: /home/fletford/Documents/flynn-fork-wildos/nebula2-wildos/training/data

data:
  batch_size: 4
  num_workers: 4
  pin_memory: True
