services:
  ros2_humble:
    image: explorfm_ros:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: explorfm_ros2_humble
    working_dir: /ros2_ws
    environment:
      - ROS_DOMAIN_ID=0
    stdin_open: true
    tty: true
    network_mode: "host"

